Repository FRONT-END-BOOTCAMP-PLUS-3/DevMate, pull requests merged in 2025-02, with the labels that each got.

#12 docs: 풀리퀘 템플릿 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📃 docs

#13 test: RTL, Vitest 설치 및 예시 추가
  __tests__/components/testExam.test.tsx
  package-lock.json
  package.json
  vite.config.ts
Labels: ⚙ 개발 환경 세팅

#8 공통 컴포넌트 제작 - badge
  components/badge/badge.module.scss
  components/badge/badge.tsx
  styles/colors.scss
Labels: ✨ feat

#15 공통 컴포넌트 제작 - table
  components/table/table.module.scss
  components/table/table.tsx
  styles/colors.scss
  styles/globals.scss
Labels: ✨ feat

#9 공통 컴포넌트 제작 - button
  components/button/button.module.scss
  components/button/button.tsx
Labels: ✨ feat

#18 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📃 docs

#20 공통 컴포넌트 제작 - modal
  components/inputFiled/InputField.module.scss
  components/inputFiled/InputFiled.tsx
  components/modal/Modal.module.scss
  components/modal/Modal.tsx
  package-lock.json
  package.json
  prisma/migrations/20250221023156_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  styles/reset.scss
Labels: ✨ feat

#21 feat: prisma SQL문 수정
  prisma/migrations/20250221065707_init/migration.sql
  prisma/schema.prisma
Labels: ✨ feat, ⚙ 개발 환경 세팅

#34 ui 구현 - 로그인 페이지
  app/(anon)/login/find/id/page.tsx
  app/(anon)/login/find/password/page.tsx
  app/(anon)/login/login.module.scss
  app/(anon)/login/page.tsx
  components/button/button.tsx
  stores/loginModalStore.ts
  styles/globals.scss
Labels: ✨ feat

#36 [feature/recuitment] 모집글 상세 페이지 작업 + 테스트 환경 세팅
  app/(anon)/recruitments/[id]/RecruitmentDetail.module.scss
  app/(anon)/recruitments/[id]/_components/CommentContent.module.scss
  app/(anon)/recruitments/[id]/_components/CommentContent.tsx
  app/(anon)/recruitments/[id]/_components/CommentContentList.module.scss
  app/(anon)/recruitments/[id]/_components/CommentContentList.tsx
  app/(anon)/recruitments/[id]/_components/CommentForm.module.scss
  app/(anon)/recruitments/[id]/_components/CommentForm.tsx
  app/(anon)/recruitments/[id]/_components/LikeButton.module.scss
  app/(anon)/recruitments/[id]/_components/LikeButton.tsx
  app/(anon)/recruitments/[id]/_components/RecruitmentContent.module.scss
  app/(anon)/recruitments/[id]/_components/RecruitmentContent.tsx
  app/(anon)/recruitments/[id]/page.tsx
  domain/entities/comment.ts
  domain/entities/project.ts
  package-lock.json
  package.json
  vite.config.ts
  vitest.setup.ts
Labels: ✨ feat, ⚙ 개발 환경 세팅

#40 service구현 - 회원 가입 페이지
  app/(anon)/signup/_components/signupForm.tsx
  app/(anon)/signup/_hooks/use-signupHandlers.ts
  app/(anon)/signup/_hooks/use-signupReducer.ts
  app/(anon)/signup/apis/checkEmailDup.ts
  app/(anon)/signup/apis/signup.ts
  app/(anon)/signup/page.tsx
  app/api/signup/checkEmail/route.ts
  app/api/signup/route.ts
  app/api/users/route.ts
  application/usecases/post/dtos/postDto.ts
  application/usecases/post/postUsecase.ts
  application/usecases/user/dtos/userDto.ts
  application/usecases/user/dtos/userPost.ts
  application/usecases/user/userAuthUsecase.ts
  application/usecases/user/userUsecase.ts
  domain/entities/user.ts
  domain/repositories/userRepository.ts
  dummy/index.ts
  infrastructure/repositories/psUserRepository.ts
  package-lock.json
  package.json
  utils/security.ts
  utils/transformUserData.ts
Labels: ✨ feat

#41 [feature/recuitmentApply] 지원하기 페이지 UI 완
  __tests__/components/RecruitmentDetail/RecruitmentContent.test.tsx
  __tests__/components/apply/Apply.test.tsx
  app/(anon)/recruitments/[id]/_components/CommentContentList.tsx
  app/(anon)/recruitments/[id]/_components/RecruitmentContent.module.scss
  app/(anon)/recruitments/[id]/_components/RecruitmentContent.tsx
  app/(anon)/recruitments/[id]/page.tsx
  app/user/recruitments/[id]/apply/Apply.module.scss
  app/user/recruitments/[id]/apply/page.tsx
  components/inputField/InputField.tsx
  styles/globals.scss
Labels: ✨ feat, ✅ test

#43 [feature/recuitmentApply] rename: 충돌 해결
  app/user/recruitments/[id]/apply/Apply.module.scss
  app/user/recruitments/[id]/apply/page.tsx
Labels: rename

#51 service구현 - 로그인 페이지
  app/(anon)/login/_actions/loginSeverAction.ts
  app/(anon)/login/page.tsx
  app/(anon)/recruitments/[id]/page.tsx
  app/(anon)/signup/apis/signup.ts
  app/api/login/route.ts
  app/api/signup/checkEmail/route.ts
  app/api/signup/route.ts
  app/user/projects/[id]/page.tsx
  application/usecases/auth/login/dtos/loginDto.ts
  application/usecases/auth/login/loginUsecase.ts
  application/usecases/auth/signup/dtos/signupDto.ts
  application/usecases/auth/signup/signupCheckEmailUsecase.ts
  application/usecases/auth/signup/signupUsecase.ts
  application/usecases/user/dtos/userDto.ts
  application/usecases/user/dtos/userPost.ts
  infrastructure/repositories/psUserRepository.ts
  middleware.ts
  package-lock.json
  package.json
  prisma/schema.prisma
  utils/transformUserData.ts
Labels: ✨ feat

#64 fix: 타입 오류 수정 (테스트, DTO)
  __tests__/app/(anon)/recruitments/[id]/_components/commentContent.test.tsx
  __tests__/app/(anon)/recruitments/[id]/_components/recruitmentContent.test.tsx
  __tests__/app/user/recruitments/[id]/apply/page.test.tsx
  application/usecases/recruitment/dtos/recruitmentDetailDto.ts
Labels: 🐞 fix
