Repository FRONT-END-BOOTCAMP-PLUS-3/DevMate, pull requests merged in 2025-03, with the labels that each got.

#74 [Feature/recuitmentDetail-server] 모집글 상세 페이지 백엔드 추가 및 연결
  app/(anon)/recruitments/[id]/_components/commentContent.module.scss
  app/(anon)/recruitments/[id]/_components/commentContent.tsx
  app/(anon)/recruitments/[id]/_components/commentContentList.module.scss
  app/(anon)/recruitments/[id]/_components/commentForm.module.scss
  app/(anon)/recruitments/[id]/_components/likeButton.tsx
  app/(anon)/recruitments/[id]/_components/recruitmentContent.module.scss
  app/(anon)/recruitments/[id]/_components/recruitmentContent.tsx
  app/(anon)/recruitments/[id]/page.tsx
  app/api/recruitments/[id]/like/route.ts
  app/api/recruitments/[id]/route.ts
  application/usecases/recruitment/dtos/recruitmentDetailDto.ts
  application/usecases/recruitment/recruitmentDetailUsecase.ts
  application/usecases/recruitment/toggleLikeUsecase.ts
  components/button/button.module.scss
  domain/repositories/likeRepository.ts
  infrastructure/repositories/psLikeRepository.ts
  infrastructure/repositories/psProjectRepository.ts
  utils/formatDateTime.ts
Labels: ✨ feat

#79 informations service
  .vscode/launch.json
  app/(anon)/login/_actions/loginSeverAction.ts
  app/(anon)/login/page.tsx
  app/(anon)/signup/_components/signupForm.tsx
  app/(anon)/signup/_hooks/use-signupHandlers.ts
  app/(anon)/signup/_hooks/use-signupReducer.ts
  app/(anon)/signup/apis/signup.ts
  app/(anon)/signup/page.tsx
  app/api/information/route.ts
  app/api/signup/route.ts
  app/api/user/route.ts
  app/user/information/_components/deleteAccountModal.module.scss
  app/user/information/_components/deleteAccountModal.tsx
  app/user/information/_components/infoUserRow.module.scss
  app/user/information/_components/infoUserRow.tsx
  app/user/information/_hooks/use-editUserInfo.ts
  app/user/information/information.module.scss
  app/user/information/page.tsx
  application/usecases/auth/signup/dtos/signupDto.ts
  application/usecases/auth/signup/signupUsecase.ts
  application/usecases/information/dtos/infoUserDto.ts
  application/usecases/information/dtos/userWithTechStackDto.ts
  application/usecases/information/updateUserInfoUsecase.ts
  application/usecases/information/userInfoUsecase.ts
  application/usecases/user/deleteAccountUsecase.ts
  application/usecases/user/userUsecase.ts
  components/header/header.tsx
  components/header/headerClient/headerClient.tsx
  domain/repositories/tagRepository.ts
  domain/repositories/techStackTagRepository.ts
  domain/repositories/userRepository.ts
  dummy/index.ts
  infrastructure/repositories/psTagRepository.ts
  infrastructure/repositories/psTechStackTagRepository.ts
  infrastructure/repositories/psUserRepository.ts
  public/test.jpg
  types/index.ts
  utils/cookie.ts
  utils/transformData.ts
  utils/transformUserData.ts
Labels: ✨ feat

#80 [feature/recruitment-create] 모집글 등록 페이지 백엔드 완성
  app/api/project/[id]/route.ts
  app/user/recruitments/create/_components/createTags/createTags.module.scss
  app/user/recruitments/create/_components/createTags/createTags.tsx
  app/user/recruitments/create/create.module.scss
  app/user/recruitments/create/page.tsx
  application/usecases/project/createProjectUsecase.ts
  application/usecases/project/dtos/createProjectDto.ts
  domain/repositories/projectRepository.ts
  domain/repositories/projectTagRepository.ts
  infrastructure/repositories/psProjectRepository.ts
  infrastructure/repositories/psProjectTagRepository.ts
Labels: ✨ feat

#78 [feature/recuitmentDetail-server] 모집글 상세 페이지 백엔드 완료
  __tests__/app/(anon)/recruitments/[id]/_components/likeButton.test.tsx
  __tests__/app/(anon)/recruitments/[id]/page.test.tsx
  app/(anon)/login/_actions/loginSeverAction.ts
  app/(anon)/recruitments/[id]/_components/actionButtons.module.scss
  app/(anon)/recruitments/[id]/_components/actionButtons.tsx
  app/(anon)/recruitments/[id]/_components/commentContent.tsx
  app/(anon)/recruitments/[id]/_components/commentContentList.tsx
  app/(anon)/recruitments/[id]/_components/commentForm.tsx
  app/(anon)/recruitments/[id]/_components/likeButton.tsx
  app/(anon)/recruitments/[id]/_components/recruitmentContent.module.scss
  app/(anon)/recruitments/[id]/_components/recruitmentContent.tsx
  app/(anon)/recruitments/[id]/page.tsx
  app/api/recruitments/[id]/comment/route.ts
  app/api/recruitments/[id]/like/route.ts
  app/api/recruitments/[id]/route.ts
  application/usecases/recruitment/createCommentUsecase.ts
  application/usecases/recruitment/createToggleLikeUsecase.ts
  application/usecases/recruitment/deleteCommentUseCase.ts
  application/usecases/recruitment/getRecruitmentDetailUsecase.ts
  domain/repositories/commentRepository.ts
  domain/repositories/projectRepository.ts
  infrastructure/repositories/psCommentRepository.ts
  infrastructure/repositories/psProjectRepository.ts
  package-lock.json
Labels: ✨ feat, ✅ test

#93 [feature/projectDetail-UI] 프로젝트 수정 페이지 구현
  __tests__/app/user/projects/[id]/_components/noticeSection.test.tsx
  __tests__/app/user/projects/[id]/dummy.ts
  __tests__/app/user/projects/[id]/mocks/handlers.ts
  __tests__/app/user/projects/[id]/mocks/server.ts
  __tests__/app/user/projects/[id]/page.test.tsx
  app/(anon)/recruitments/_components/recruitmentsFilters/recruitmentsFilters.module.scss
  app/api/project/[id]/route.ts
  app/user/projects/[id]/edit/edit.module.scss
  app/user/projects/[id]/edit/page.tsx
  app/user/projects/[id]/page.tsx
  app/user/projects/[id]/projectDetail.module.scss
  app/user/recruitments/myComment/myComment.module.scss
  app/user/recruitments/myCreate/myCreate.module.scss
  app/user/recruitments/myLike/myLike.module.scss
  application/usecases/project/dtos/projectDetailDto.ts
  application/usecases/project/dtos/updateProjectDto.ts
  application/usecases/project/getProjectDetailUsecase.ts
  application/usecases/project/updateProjectUsecase.ts
  components/footer/footer.module.scss
  components/header/header.module.scss
  infrastructure/repositories/psProjectTagRepository.ts
  package.json
  public/mockServiceWorker.js
Labels: ✨ feat

#97 [Feature/apply server] 모집글 리스트 백엔드 추가 및 연결 완료
  .gitignore
  app/(anon)/recruitments/[id]/_components/actionButtons.tsx
  app/(anon)/recruitments/[id]/_components/recruitmentContent.tsx
  app/(anon)/recruitments/[id]/page.tsx
  app/(anon)/recruitments/_components/recruitmentsFilters/recruitmentsFilters.tsx
  app/(anon)/recruitments/_components/recruitmentsItem/recruitmentsItem.tsx
  app/(anon)/recruitments/_components/recruitmentsSearch/recruitmentsSearch.tsx
  app/(anon)/recruitments/_components/recruitmentsSortFilters/recruitmentsSortFilters.tsx
  app/(anon)/recruitments/_components/recruitmentsTagSearch/recruitmentsTagSearch.module.scss
  app/(anon)/recruitments/_components/recruitmentsTagSearch/recruitmentsTagSearch.tsx
  app/(anon)/recruitments/page.tsx
  app/api/recruitments/[id]/apply/route.ts
  app/api/recruitments/route.ts
  app/user/recruitments/[id]/apply/apply.module.scss
  app/user/recruitments/[id]/apply/page.tsx
  application/usecases/recruitment/createApplyUsecase.ts
  application/usecases/recruitment/dtos/ApplyInputDto.ts
  application/usecases/recruitment/dtos/rectuitmentsDto.ts
  application/usecases/recruitment/getProjectTitleUsecase.ts
  application/usecases/recruitment/getRecruitmentsUsecase.ts
  domain/repositories/applyRepository.ts
  domain/repositories/projectRepository.ts
  infrastructure/repositories/psApplyRepository.ts
  infrastructure/repositories/psProjectRepository.ts
  utils/fileStorage.ts
Labels: ✨ feat

#98 feat: repository prisma.disconnect 추가
  infrastructure/repositories/psApplyRepository.ts
  infrastructure/repositories/psCommentRepository.ts
  infrastructure/repositories/psLikeRepository.ts
  infrastructure/repositories/psMemberRepository.ts
  infrastructure/repositories/psProjectRepository.ts
  infrastructure/repositories/psProjectTagRepository.ts
  infrastructure/repositories/psTagRepository.ts
  infrastructure/repositories/psTechStackTagRepository.ts
  infrastructure/repositories/psUserRepository.ts
Labels: ✨ feat

#99 [feature/recruitments-server] 모집글 리스트(메인 페이지) 수정
  app/(anon)/recruitments/_components/recruitmentsItem/recruitmentsItem.module.scss
  app/(anon)/recruitments/_components/recruitmentsItem/recruitmentsItem.tsx
  app/(anon)/recruitments/_components/recruitmentsTagSearch/recruitmentsTagSearch.module.scss
  app/(anon)/recruitments/mockData.ts
  app/(anon)/recruitments/page.tsx
  app/(anon)/recruitments/recruitments.module.scss
Labels: ✨ feat, 🐞 fix

#104 [feature/my project server] 마이페이지 백엔드 완료
  app/(anon)/recruitments/_components/recruitmentsTagSearch/recruitmentsTagSearch.tsx
  app/api/project/myPage/route.ts
  application/usecases/project/getMyProjectsUsecase.ts
  domain/repositories/projectRepository.ts
  infrastructure/repositories/psProjectRepository.ts
  utils/service/getMyProjects.ts
Labels: ✨ feat

#109 [fix] project create 페이지 데이터 전송 버그 수정
  app/user/recruitments/(handle)/create/page.tsx
Labels: 🐞 fix

#110 [feature/myProject-server] 마이페이지 프로젝트 조회 백엔드 연결
  __tests__/app/(anon)/recruitments/page.test.tsx
  app/user/projects/_components/myProjectItem/myProjectItem.module.scss
  app/user/projects/_components/myProjectItem/myProjectItem.tsx
  app/user/projects/myOpen/myOpen.module.scss
  app/user/projects/myOpen/page.tsx
  app/user/projects/myParticipate/myParticipate.module.scss
  app/user/projects/myParticipate/page.tsx
  app/user/recruitments/(my)/myApplyStatus/myApplyStatus.module.scss
  app/user/recruitments/(post)/layout.module.scss
  app/user/recruitments/(post)/myComment/myComment.module.scss
  app/user/recruitments/(post)/myCreate/myCreate.module.scss
  app/user/recruitments/(post)/myLike/myLike.module.scss
Labels: ✨ feat

#108 [feature/mypage-applyStatus] 사소한 수정사항들
  app/api/recruitments/myApplyStatus/route.ts
  app/user/recruitments/(my)/myApplyStatus/_components/myApplyStatusItem.module.scss
  app/user/recruitments/(my)/myApplyStatus/_components/myApplyStatusItem.tsx
  app/user/recruitments/(my)/myApplyStatus/myApplyStatus.module.scss
  app/user/recruitments/(my)/myApplyStatus/page.tsx
  application/usecases/recruitment/dtos/myApply/myApplyProjectDto.ts
  application/usecases/recruitment/getMyApplyStatusUsecase.ts
  infrastructure/repositories/psApplyRepository.ts
Labels: 🔧 refactor

#112 [Feature/my project server] 빌드 오류 수정
  app/(anon)/recruitments/[id]/page.tsx
  app/(anon)/recruitments/page.tsx
  app/user/information/information.module.scss
  app/user/projects/_components/myProjectItem/myProjectItem.module.scss
  app/user/recruitments/(post)/_components/myRecruitmentItem/myRecruitmentItem.module.scss
  infrastructure/repositories/psProjectRepository.ts
Labels: ✨ feat

#114 [feature/recruitmentDetail-server] 유스케이스 타입 오류 수정
  app/(anon)/recruitments/_components/recruitmentsItem/recruitmentsItem.tsx
  app/(anon)/recruitments/page.tsx
  app/user/projects/_components/myProjectItem/myProjectItem.tsx
  app/user/projects/myOpen/page.tsx
  app/user/projects/myParticipate/page.tsx
  app/user/recruitments/(post)/myComment/page.tsx
  app/user/recruitments/(post)/myCreate/page.tsx
  app/user/recruitments/(post)/myLike/page.tsx
  application/usecases/project/getMyProjectsUsecase.ts
  application/usecases/recruitment/dtos/recruitmentsDto.ts
  application/usecases/recruitment/getRecruitmentsUsecase.ts
  infrastructure/repositories/psProjectRepository.ts
Labels: ✨ feat, 🐞 fix

#117 docs: Update README.md
  README.md
Labels: 📃 docs

#127 [refactor/yezzero] recruitmentsCreate / myApplyStatus / projectDetail / projectEdit 페이지
  app/user/projects/[id]/_components/applicantDetails.tsx
  app/user/projects/[id]/_components/applicationsSection.tsx
  app/user/projects/[id]/_components/membersSection.tsx
  app/user/projects/[id]/_components/noticeSection.tsx
  app/user/projects/[id]/edit/page.tsx
  app/user/projects/[id]/page.tsx
  app/user/projects/[id]/projectDetail.module.scss
  app/user/recruitments/(handle)/create/_components/createTags/createTags.module.scss
  app/user/recruitments/(handle)/create/page.tsx
  app/user/recruitments/(my)/myApplyStatus/_components/myApplyStatusItem.tsx
  app/user/recruitments/(my)/myApplyStatus/myApplyStatus.module.scss
  app/user/recruitments/(my)/myApplyStatus/page.tsx
  application/usecases/dtos/applyDto.ts
  application/usecases/project/getProjectDetailUsecase.ts
  application/usecases/project/rejectApplicantUsecase.ts
  application/usecases/recruitment/dtos/ApplyInputDto.ts
  application/usecases/recruitment/getMyApplyStatusUsecase.ts
  components/table/table.tsx
  domain/repositories/applyRepository.ts
  infrastructure/repositories/psApplyRepository.ts
  infrastructure/repositories/psTagRepository.ts
  utils/formatDateTime.ts
  utils/formatDateToString.ts
Labels: ✨ feat, 🔧 refactor

#128 [Refactor/boyoung] UI 및 기능 수정
  app/(anon)/recruitments/[id]/_components/actionButtons.tsx
  app/(anon)/recruitments/[id]/_components/commentForm.tsx
  app/(anon)/recruitments/[id]/_components/recruitmentContent.tsx
  app/(anon)/recruitments/_components/recruitmentsSortFilters/recruitmentsSortFilters.tsx
  app/api/recruitments/[id]/apply/route.ts
  app/api/recruitments/route.ts
  app/user/projects/_components/myProjectItem/myProjectItem.module.scss
  app/user/projects/_components/myProjectItem/myProjectItem.tsx
  app/user/projects/myOpen/page.tsx
  app/user/projects/myParticipate/page.tsx
  app/user/recruitments/(handle)/[id]/apply/apply.module.scss
  app/user/recruitments/(handle)/[id]/apply/page.tsx
  app/user/recruitments/(post)/myLike/page.tsx
  application/usecases/recruitment/getProjectTitleUsecase.ts
  application/usecases/recruitment/getRecruitmentsUsecase.ts
  components/button/button.module.scss
  components/button/button.tsx
  constants/recruitmentTypes.ts
  domain/repositories/projectRepository.ts
  infrastructure/repositories/psProjectRepository.ts
Labels: 📃 docs, ✨ feat, 🔧 refactor

#129 feat: 토큰 없음 오류 처리 console.log로 변경
  app/(anon)/recruitments/[id]/_components/recruitmentContent.tsx
  utils/cookie.ts
Labels: ✨ feat

#131 [refactor/yezzero] 수정
  app/user/projects/[id]/page.tsx
  application/usecases/project/getProjectDetailUsecase.ts
  application/usecases/recruitment/getMyApplyStatusUsecase.ts
Labels: 🔧 refactor

#136 test: 테스트 코드 오류 수정
  __tests__/app/(anon)/recruitments/[id]/_components/commentForm.test.tsx
  __tests__/app/(anon)/recruitments/[id]/_components/likeButton.test.test.tsx
  __tests__/app/(anon)/recruitments/[id]/_components/recruitmentContent.test.tsx
  __tests__/app/user/projects/[id]/_components/applicationSection.test.tsx
  __tests__/app/user/projects/[id]/_components/membersSection.test.tsx
  __tests__/app/user/projects/[id]/page.test.tsx
  __tests__/e2e/(anon)/recruitments/[id]/page.test.tsx
Labels: ✅ test
